### ISSUE TITLE
When no outer `describe()` is used, testsuite name is undefined

### ISSUE THREAD

**Issue by danjamin** [palmerj3/jest-junit#13]
If a unit test is written without an outer `describe()` -- which by the way should be optional, then `jest-junit` sets the testsuite name to `undefined`.

There should be a way to configure using the test file path instead of the outermost `describe()`.

**Comment by palmerj3** [comment]
@danjamin published your PR as 1.5.0. Thanks again!
https://github.com/palmerj3/jest-junit/releases/tag/v1.5.0

**Comment by danjamin** [comment]
@palmerj3 no problem; thanks for the quick turn around
