### ISSUE TITLE
Add coverage output generated xml

### ISSUE THREAD

**Issue by robinvdvleuten** [palmerj3/jest-junit#16]
Hi there,

I use this project very successfully on our CI in combination with __create-react-app__;

```bash
yarn test -- --testResultsProcessor jest-junit
```

Now I was thinking if it is possible to add the code coverage report to the generated _junit.xml_? Thanks in advance for any help! 

Cheers!

**Comment by palmerj3** [comment]
@robinvdvleuten great idea! I'll look into it and see what would be involved in adding it.

Feel free to submit a PR if you have time!

**Comment by robinvdvleuten** [comment]
@palmerj3 sure, I've already created a fork for it 👍

**Comment by robinvdvleuten** [comment]
@palmerj3 are you aware of the expected coverage format?

**Comment by palmerj3** [comment]
@robinvdvleuten sorry for not responding sooner!

The junit spec seems like it's not super locked down. But the one I've been following for this project is is [IBM's](https://www.ibm.com/support/knowledgecenter/en/SSQ2R2_9.5.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html).

I don't see any specific tags mentioned for coverage.
What are the needs you have?

It's always possible to set them as properties of the testsuite and/or testcase tags.s

**Comment by palmerj3** [comment]
Since there doesn't appear to be any area in the junit xml spec to contain coverage information I'm going to close this issue.
