### ISSUE TITLE
Allow customization of separator between ancestor titles

### ISSUE THREAD

**Issue by yangshun** [palmerj3/jest-junit#19]
In the [code](https://github.com/palmerj3/jest-junit/blob/master/utils/buildJsonResults.js#L49), I saw the `ancestorTitles` are concatenated using a space. In Jest, by default they use the `›` character to concatenate the strings between hierarchies and I think it would be good to allow users to customize this character. 

If you are agreeable with this I can create a PR to implement this. I'm thinking of implementing this through the env variable like how the class name template is done.

**Comment by palmerj3** [comment]
@yangshun that sounds reasonable to me :)  Feel free to submit a PR.

Just please make sure this new configuration works both as an env variable and a package.json config variable (since we're supporting both for all configurations).

**Comment by yangshun** [comment]
Got it! I'll get to it soon (:
