### ISSUE TITLE
Fail when using from cli with --projects

### ISSUE THREAD

**Issue by rosieks** [palmerj3/jest-junit#23]
When I use the following command:

    jest --testResultProcess ./node_modules/jest-junit --projects proj1 proj2

it fails because cannot find _packages.json_ file. It's probably due to this line: https://github.com/palmerj3/jest-junit/blob/8e5a183aa034efeaf34def5b537136f2dcb63c32/utils/getOptions.js#L20
Could you make it optional or even better - find it based on `testFilePath`

**Comment by palmerj3** [comment]
@rosieks thank you for reporting! I will flag this as a bug and look into fixing it so it can work in multi-project and single project. Feel free to submit a PR if you have ideas :)

**Comment by palmerj3** [comment]
Hey @rosieks I pushed a release [v3.0.0](https://github.com/palmerj3/jest-junit/releases/tag/v3.0.0) which fixes this issue. Please give it a shot and let me know if you have any issues.

Thanks for reporting!!
