### ISSUE TITLE
Nested testsuites instead of ancestors

### ISSUE THREAD

**Issue by Multiply** [palmerj3/jest-junit#25]
Would it be possible to use `ancestors` as a way of defining nested testsuites?

Ideally, what I'd like to achieve:
- Each file is a testsuite
  - Name is based on the top-level `describe` inside the file, if there's only _one_ top-level `describe`.
  - Name is based on the filename, if there's _multiple_ top-level `describe`.
- Each `describe` is their own nested testsuite, under the file testsuite.
  - For every child `describe`, they are nested under the parent `describe` as a new testsuite.

**Comment by palmerj3** [comment]
@Multiply thanks for submitting an issue.

In this case I would recommend that you fork the repo and make the change on your fork.
