### ISSUE TITLE
Don't fail if application is located in root directory

### ISSUE THREAD

**Issue by kolo** [palmerj3/jest-junit#27]
HI,

library throws an error if application is located in root directory.

```
Error: Unable to locate package.json starting at /
    at getAppOptions (/node_modules/jest-junit/utils/getOptions.js:40:9)
    at module.exports (/node_modules/jest-junit/utils/getOptions.js:44:55)
    at module.exports (/node_modules/jest-junit/index.js:23:19)
```

I came across this error then tried to get report while running tests in docker container. There is a simple workaround this problem, which is changing working dir to non-root directory, so I'm not sure that it should be fixed.

**Comment by palmerj3** [comment]
@kolo can you show me your jest config?

I'm assuming if you use `<rootDir>` you should be fine. E.g. 

```
{
  testResultsProcessor: '<rootDir>/node_modules/jest-junit'
}
```

**Comment by palmerj3** [comment]
Ahhh ok I think I see the issue.. https://github.com/palmerj3/jest-junit/blob/master/utils/getOptions.js#L24

I'll file this as a bug and submit a fix later this evening.

**Comment by palmerj3** [comment]
@kolo I've added support for this in https://github.com/palmerj3/jest-junit/pull/28

Will be publishing 3.1.0 shortly.
