### ISSUE TITLE
add support for jest 22

### ISSUE THREAD

**Issue by shai32** [palmerj3/jest-junit#36]

**Comment by palmerj3** [comment]
@shai32 do you have details about what breaks?

**Comment by palmerj3** [comment]
I am currently re-configuring the travis tests so it tests againt multiple versions of jest. Once I have that setup I'll dig in a bit deeper with jest 22.

**Comment by palmerj3** [comment]
@shai32 so I did some work tonight and added some travis checks to test jest-junit against multiple versions of jest.

As you can see here there doesn't appear to be an issue with jest 22. But if you can provide some additional details I'd be happy to take a look.

https://github.com/palmerj3/jest-junit/pull/38
https://travis-ci.org/palmerj3/jest-junit/builds/320048675

**Comment by shai32** [comment]
after upgrading the jest, I had this error
![image](https://user-images.githubusercontent.com/16700996/34458860-4b6eb8d0-edea-11e7-9bcc-01b2e3acade0.png)
after investigating the problem, I found out its related to create-react-app and not for jest-junit
closing the issue

**Comment by palmerj3** [comment]
Ah yes I actually commented on another issue similar to this recently. create-react-app has scripts which invoke jest programmatically and, thus, it's pinned to a particular version of jest. There are already issues on the create-react-app repo for upgrading jest so I would definitely suggest following those.
