### ISSUE TITLE
Error: Cannot find module ''jest-junit''

### ISSUE THREAD

**Issue by ryanvgates** [palmerj3/jest-junit#50]
I have installed jest and jest-junit as devDependencies in my project. However when I try to run the command from the [example](https://github.com/palmerj3/jest-junit#usage), I get the following error.

<pre>● Validation Error:

  Module 'jest-junit' in the testResultsProcessor option was not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html</pre>

I am using the command

`jest --ci --testResultsProcessor='jest-junit'`

in the scripts section of my package.json. Please let me know if you need any additional information or can't reproduce the issue.

**Comment by palmerj3** [comment]
@ryanvgates I think you may have installed an old version of jest or have some symlink in place. Older versions of jest don't recognize the --ci flag, for instance.

I just followed the guide and was able to get jest-junit running with jest.

Perhaps try this as a fail-safe to make sure you're using the version of jest in node_modules and not some globally installed jest.

Put the following in your package.json:

```
  "scripts": {
    "test": "jest --ci --testResultsProcessor=\"jest-junit\""
  }
```

Then invoke with npm:

```
npm run test
```

**Comment by ryanvgates** [comment]
Thank you for your help. I found my issue. It had to do with the `test` command in the `scripts` section of the `package.json`.

This works.
<pre>"scripts": {
    "test": "jest --forceExit --ci --testResultsProcessor=\"jest-junit\""
  }</pre>

This works.
<pre>"scripts": {
    "test": "jest --forceExit --ci --testResultsProcessor=jest-junit"
  }</pre>

This does **not** work.
<pre>"scripts": {
    "test": "jest --forceExit --ci --testResultsProcessor='jest-junit'"
  }</pre>

I had to add [`--forceExit`](https://facebook.github.io/jest/docs/en/cli.html#forceexit) since the process wasn't returning. The [`--ci`](https://facebook.github.io/jest/docs/en/cli.html#ci) error went away after deleting `node_modules` and running `npm ci`.
