### ISSUE TITLE
Node v4 support

### ISSUE THREAD

**Issue by crudo** [palmerj3/jest-junit#7]
Hi @palmerj3, thanks for you reporter. 

Is there a reason why you require node >=5?  I was trying to run in on node 4 (v4.8.0) and it worked too.

We have node 4 on our CI, and it would be great, if we could lower the required node in your package.json to 4.

Thanks!

**Comment by palmerj3** [comment]
@crudo thank you! I merged your PR and bumped the version to 1.3.0. Did a minor bump just in case, although I don't foresee any breaking changes.
